-- =============================================================================
-- Gypsum Sales CRM V2
-- Migration: 20261003000002_v2_shipment_rls.sql
--
-- Purpose:
--   Secure the V2 shipment foundation with Row Level Security.
--
-- Tables:
--   vehicles
--   drivers
--   shipments
--   shipment_items
--
-- Design:
--   - Tenant isolation by company_id
--   - Authenticated users only
--   - Same security pattern already used by V1
--   - Detailed role/permission restrictions will be added later
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. ENABLE RLS
-- =============================================================================

ALTER TABLE public.vehicles
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.drivers
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.shipments
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.shipment_items
  ENABLE ROW LEVEL SECURITY;


-- =============================================================================
-- 2. VEHICLES RLS
-- =============================================================================

DROP POLICY IF EXISTS vehicles_company_isolation
ON public.vehicles;

CREATE POLICY vehicles_company_isolation
  ON public.vehicles
  FOR ALL
  TO authenticated
  USING (
    company_id = public.auth_user_company_id()
  )
  WITH CHECK (
    company_id = public.auth_user_company_id()
  );


-- =============================================================================
-- 3. DRIVERS RLS
-- =============================================================================

DROP POLICY IF EXISTS drivers_company_isolation
ON public.drivers;

CREATE POLICY drivers_company_isolation
  ON public.drivers
  FOR ALL
  TO authenticated
  USING (
    company_id = public.auth_user_company_id()
  )
  WITH CHECK (
    company_id = public.auth_user_company_id()
  );


-- =============================================================================
-- 4. SHIPMENTS RLS
-- =============================================================================

DROP POLICY IF EXISTS shipments_company_isolation
ON public.shipments;

CREATE POLICY shipments_company_isolation
  ON public.shipments
  FOR ALL
  TO authenticated
  USING (
    company_id = public.auth_user_company_id()
  )
  WITH CHECK (
    company_id = public.auth_user_company_id()
  );


-- =============================================================================
-- 5. SHIPMENT ITEMS RLS
-- =============================================================================

DROP POLICY IF EXISTS shipment_items_company_isolation
ON public.shipment_items;

CREATE POLICY shipment_items_company_isolation
  ON public.shipment_items
  FOR ALL
  TO authenticated
  USING (
    company_id = public.auth_user_company_id()
  )
  WITH CHECK (
    company_id = public.auth_user_company_id()
  );


-- =============================================================================
-- 6. TABLE GRANTS
-- =============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.vehicles
TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.drivers
TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.shipments
TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.shipment_items
TO authenticated;


-- =============================================================================
-- 7. SEQUENCE ACCESS
-- =============================================================================
-- Shipment numbers are generated by PostgreSQL identity.

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO authenticated;


-- =============================================================================
-- 8. COMMENTS
-- =============================================================================

COMMENT ON POLICY vehicles_company_isolation
ON public.vehicles IS
  'Tenant isolation for V2 vehicles.';

COMMENT ON POLICY drivers_company_isolation
ON public.drivers IS
  'Tenant isolation for V2 drivers.';

COMMENT ON POLICY shipments_company_isolation
ON public.shipments IS
  'Tenant isolation for V2 shipments.';

COMMENT ON POLICY shipment_items_company_isolation
ON public.shipment_items IS
  'Tenant isolation for V2 shipment items.';

COMMIT;