-- =============================================================================
-- Gypsum Sales CRM — Waybills and Loading Confirmation
-- =============================================================================
-- Flow:
--   confirmed order -> order item -> waybill -> waybill number
--   -> loading confirmation
--
-- Design rules:
--   * Waybills belong to an order and are tenant-scoped by company_id.
--   * A waybill item belongs to exactly one order item.
--   * A waybill can only be created for a confirmed order.
--   * One active waybill is allowed per order item.
--   * Product / quantity / weight are snapshotted on the waybill item.
--   * Waybill numbers are generated by PostgreSQL and are unique.
--   * Loading confirmation is kept in a separate 1:1 table.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. ENUMS
-- =============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typnamespace = 'public'::regnamespace
      AND typname = 'waybill_status'
  ) THEN
    CREATE TYPE public.waybill_status AS ENUM (
      'draft',
      'issued',
      'loading_confirmed',
      'cancelled'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typnamespace = 'public'::regnamespace
      AND typname = 'loading_status'
  ) THEN
    CREATE TYPE public.loading_status AS ENUM (
      'pending',
      'confirmed',
      'cancelled'
    );
  END IF;
END $$;


-- =============================================================================
-- 2. WAYBILLS
-- =============================================================================

CREATE TABLE public.waybills (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  company_id uuid NOT NULL
    REFERENCES public.companies (id)
    ON DELETE RESTRICT,

  order_id uuid NOT NULL
    REFERENCES public.orders (id)
    ON DELETE RESTRICT,

  -- System generated unique waybill number
  waybill_number bigint
    GENERATED ALWAYS AS IDENTITY
    UNIQUE,

  -- Stored as Gregorian date in database.
  -- UI will display Jalali date.
  waybill_date date NOT NULL
    DEFAULT (timezone('utc', now()))::date,

  status public.waybill_status NOT NULL
    DEFAULT 'draft',

  notes text,

  issued_at timestamptz,

  issued_by uuid
    REFERENCES public.users (id)
    ON DELETE RESTRICT,

  created_at timestamptz NOT NULL
    DEFAULT timezone('utc', now()),

  updated_at timestamptz NOT NULL
    DEFAULT timezone('utc', now()),

  deleted_at timestamptz,

  CONSTRAINT waybills_issued_fields_consistent
  CHECK (
    (
      status = 'draft'
      AND issued_at IS NULL
    )
    OR
    status IN (
      'issued',
      'loading_confirmed',
      'cancelled'
    )
  )
);


-- =============================================================================
-- 3. WAYBILLS INDEXES
-- =============================================================================

CREATE INDEX idx_waybills_company_id
  ON public.waybills (company_id)
  WHERE deleted_at IS NULL;


CREATE INDEX idx_waybills_order_id
  ON public.waybills (
    company_id,
    order_id
  )
  WHERE deleted_at IS NULL;


CREATE INDEX idx_waybills_status
  ON public.waybills (
    company_id,
    status,
    waybill_date DESC
  )
  WHERE deleted_at IS NULL;


CREATE INDEX idx_waybills_date
  ON public.waybills (
    company_id,
    waybill_date DESC
  )
  WHERE deleted_at IS NULL;


-- =============================================================================
-- 4. WAYBILLS TRIGGERS
-- =============================================================================

CREATE TRIGGER trg_waybills_updated_at
  BEFORE UPDATE ON public.waybills
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER trg_waybills_prevent_hard_delete
  BEFORE DELETE ON public.waybills
  FOR EACH ROW
  EXECUTE FUNCTION public.prevent_hard_delete();


-- =============================================================================
-- 5. WAYBILLS COMMENTS
-- =============================================================================

COMMENT ON TABLE public.waybills IS
  'Delivery/loading waybills issued from confirmed sales orders.';

COMMENT ON COLUMN public.waybills.waybill_number IS
  'System-generated unique waybill number.';


-- =============================================================================
-- 6. WAYBILL ITEMS
-- =============================================================================

CREATE TABLE public.waybill_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  company_id uuid NOT NULL
    REFERENCES public.companies (id)
    ON DELETE RESTRICT,

  waybill_id uuid NOT NULL
    REFERENCES public.waybills (id)
    ON DELETE RESTRICT,

  order_item_id uuid NOT NULL
    REFERENCES public.order_items (id)
    ON DELETE RESTRICT,

  product_id uuid NOT NULL
    REFERENCES public.products (id)
    ON DELETE RESTRICT,

  -- Snapshot values
  product_name_snapshot text NOT NULL,

  quantity integer NOT NULL,

  weight_kg_snapshot smallint NOT NULL,

  -- Automatic tonnage calculation
  tonnage numeric(14, 4)
    GENERATED ALWAYS AS (
      (
        quantity::numeric
        *
        weight_kg_snapshot::numeric
      ) / 1000.0
    )
    STORED,

  created_at timestamptz NOT NULL
    DEFAULT timezone('utc', now()),

  updated_at timestamptz NOT NULL
    DEFAULT timezone('utc', now()),

  deleted_at timestamptz,

  CONSTRAINT waybill_items_quantity_positive
    CHECK (quantity > 0),

  CONSTRAINT waybill_items_weight_kg_valid
    CHECK (weight_kg_snapshot IN (25, 30))
);


-- =============================================================================
-- 7. WAYBILL ITEMS INDEXES
-- =============================================================================

CREATE INDEX idx_waybill_items_company_id
  ON public.waybill_items (company_id)
  WHERE deleted_at IS NULL;


CREATE INDEX idx_waybill_items_waybill_id
  ON public.waybill_items (waybill_id)
  WHERE deleted_at IS NULL;


CREATE INDEX idx_waybill_items_order_item_id
  ON public.waybill_items (
    company_id,
    order_item_id
  )
  WHERE deleted_at IS NULL;


CREATE INDEX idx_waybill_items_product_id
  ON public.waybill_items (
    company_id,
    product_id
  )
  WHERE deleted_at IS NULL;


-- =============================================================================
-- 8. ONE ACTIVE WAYBILL PER ORDER ITEM
-- =============================================================================

CREATE UNIQUE INDEX uq_waybill_items_active_order_item
  ON public.waybill_items (
    company_id,
    order_item_id
  )
  WHERE deleted_at IS NULL;


-- =============================================================================
-- 9. WAYBILL ITEMS TRIGGERS
-- =============================================================================

CREATE TRIGGER trg_waybill_items_updated_at
  BEFORE UPDATE ON public.waybill_items
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER trg_waybill_items_prevent_hard_delete
  BEFORE DELETE ON public.waybill_items
  FOR EACH ROW
  EXECUTE FUNCTION public.prevent_hard_delete();


-- =============================================================================
-- 10. WAYBILL ITEMS COMMENTS
-- =============================================================================

COMMENT ON TABLE public.waybill_items IS
  'Waybill line items linked to order items with product and weight snapshots.';


-- =============================================================================
-- 11. LOADING
-- =============================================================================
-- One active loading record per waybill.
-- =============================================================================

CREATE TABLE public.loading (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  company_id uuid NOT NULL
    REFERENCES public.companies (id)
    ON DELETE RESTRICT,

  waybill_id uuid NOT NULL
    REFERENCES public.waybills (id)
    ON DELETE RESTRICT,

  status public.loading_status NOT NULL
    DEFAULT 'pending',

  -- Stored as Gregorian date.
  loading_date date,

  confirmed_at timestamptz,

  confirmed_by uuid
    REFERENCES public.users (id)
    ON DELETE RESTRICT,

  notes text,

  created_at timestamptz NOT NULL
    DEFAULT timezone('utc', now()),

  updated_at timestamptz NOT NULL
    DEFAULT timezone('utc', now()),

  deleted_at timestamptz,

  CONSTRAINT loading_confirmation_fields_consistent
  CHECK (
    (
      status = 'confirmed'
      AND confirmed_at IS NOT NULL
      AND confirmed_by IS NOT NULL
    )
    OR
    (
      status IN ('pending', 'cancelled')
      AND confirmed_at IS NULL
      AND confirmed_by IS NULL
    )
  )
);


-- =============================================================================
-- 12. LOADING INDEXES
-- =============================================================================

CREATE UNIQUE INDEX uq_loading_active_waybill
  ON public.loading (
    company_id,
    waybill_id
  )
  WHERE deleted_at IS NULL;


CREATE INDEX idx_loading_company_id
  ON public.loading (company_id)
  WHERE deleted_at IS NULL;


CREATE INDEX idx_loading_waybill_id
  ON public.loading (
    company_id,
    waybill_id
  )
  WHERE deleted_at IS NULL;


CREATE INDEX idx_loading_status
  ON public.loading (
    company_id,
    status,
    loading_date DESC
  )
  WHERE deleted_at IS NULL;


-- =============================================================================
-- 13. LOADING TRIGGERS
-- =============================================================================

CREATE TRIGGER trg_loading_updated_at
  BEFORE UPDATE ON public.loading
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER trg_loading_prevent_hard_delete
  BEFORE DELETE ON public.loading
  FOR EACH ROW
  EXECUTE FUNCTION public.prevent_hard_delete();


-- =============================================================================
-- 14. LOADING COMMENT
-- =============================================================================

COMMENT ON TABLE public.loading IS
  'Loading confirmation record for a waybill; one active record per waybill.';


-- =============================================================================
-- 15. VALIDATE WAYBILL -> ORDER
-- =============================================================================
-- Waybill can only be created for a confirmed order.
-- Also validates company_id consistency.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.validate_waybill_company_and_order()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_order_company uuid;
  v_order_status public.order_status;
BEGIN

  SELECT
    o.company_id,
    o.status
  INTO
    v_order_company,
    v_order_status
  FROM public.orders o
  WHERE o.id = NEW.order_id;

  IF v_order_company IS NULL THEN
    RAISE EXCEPTION
      'Order % does not exist',
      NEW.order_id;
  END IF;


  IF NEW.company_id <> v_order_company THEN
    RAISE EXCEPTION
      'Waybill company_id does not match order company_id';
  END IF;


  IF v_order_status <> 'confirmed' THEN
    RAISE EXCEPTION
      'A waybill can only be created for a confirmed order';
  END IF;


  -- Automatically populate issued_at
  IF NEW.status IN (
    'issued',
    'loading_confirmed'
  )
  AND NEW.issued_at IS NULL
  THEN
    NEW.issued_at :=
      timezone('utc', now());
  END IF;


  RETURN NEW;
END;
$$;


CREATE TRIGGER trg_validate_waybill_company_and_order
  BEFORE INSERT OR UPDATE ON public.waybills
  FOR EACH ROW
  EXECUTE FUNCTION public.validate_waybill_company_and_order();


-- =============================================================================
-- 16. VALIDATE WAYBILL ITEM LINKS
-- =============================================================================
-- Ensures:
--   order_item belongs to the same order
--   product matches order item
--   quantity matches order item
--   weight matches order item
--   company_id matches
-- =============================================================================

CREATE OR REPLACE FUNCTION public.validate_waybill_item_links()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_item_company uuid;
  v_item_order_id uuid;
  v_item_product_id uuid;
  v_item_quantity integer;
  v_item_weight smallint;

  v_waybill_company uuid;
  v_waybill_order_id uuid;
  v_waybill_status public.waybill_status;

  v_product_name text;
BEGIN

  -- ---------------------------------------------------------------------------
  -- Get order item
  -- ---------------------------------------------------------------------------

  SELECT
    oi.company_id,
    oi.order_id,
    oi.product_id,
    oi.quantity,
    oi.weight_kg_snapshot
  INTO
    v_item_company,
    v_item_order_id,
    v_item_product_id,
    v_item_quantity,
    v_item_weight
  FROM public.order_items oi
  WHERE oi.id = NEW.order_item_id
    AND oi.deleted_at IS NULL;


  IF v_item_company IS NULL THEN
    RAISE EXCEPTION
      'Order item % does not exist or is deleted',
      NEW.order_item_id;
  END IF;


  -- ---------------------------------------------------------------------------
  -- Get waybill
  -- ---------------------------------------------------------------------------

  SELECT
    w.company_id,
    w.order_id,
    w.status
  INTO
    v_waybill_company,
    v_waybill_order_id,
    v_waybill_status
  FROM public.waybills w
  WHERE w.id = NEW.waybill_id
    AND w.deleted_at IS NULL;


  IF v_waybill_company IS NULL THEN
    RAISE EXCEPTION
      'Waybill % does not exist or is deleted',
      NEW.waybill_id;
  END IF;


  -- ---------------------------------------------------------------------------
  -- Company validation
  -- ---------------------------------------------------------------------------

  IF NEW.company_id <> v_waybill_company
     OR NEW.company_id <> v_item_company
  THEN
    RAISE EXCEPTION
      'Company mismatch between waybill item, waybill and order item';
  END IF;


  -- ---------------------------------------------------------------------------
  -- Order validation
  -- ---------------------------------------------------------------------------

  IF v_item_order_id <> v_waybill_order_id THEN
    RAISE EXCEPTION
      'Order item % does not belong to waybill order %',
      NEW.order_item_id,
      v_waybill_order_id;
  END IF;


  -- ---------------------------------------------------------------------------
  -- Product validation
  -- ---------------------------------------------------------------------------

  IF NEW.product_id <> v_item_product_id THEN
    RAISE EXCEPTION
      'Waybill item product does not match order item product';
  END IF;


  -- ---------------------------------------------------------------------------
  -- Quantity validation
  -- ---------------------------------------------------------------------------

  IF NEW.quantity <> v_item_quantity THEN
    RAISE EXCEPTION
      'Waybill item quantity must match the order item quantity';
  END IF;


  -- ---------------------------------------------------------------------------
  -- Weight validation
  -- ---------------------------------------------------------------------------

  IF NEW.weight_kg_snapshot <> v_item_weight THEN
    RAISE EXCEPTION
      'Waybill item weight must match the order item weight';
  END IF;


  -- ---------------------------------------------------------------------------
  -- Prevent modification after final states
  -- ---------------------------------------------------------------------------

  IF v_waybill_status IN (
    'loading_confirmed',
    'cancelled'
  )
  THEN
    RAISE EXCEPTION
      'Items cannot be added or changed after loading confirmation or cancellation';
  END IF;


  -- ---------------------------------------------------------------------------
  -- Automatically populate product snapshot if empty
  -- ---------------------------------------------------------------------------

  IF NEW.product_name_snapshot IS NULL
     OR btrim(NEW.product_name_snapshot) = ''
  THEN

    SELECT p.name
    INTO v_product_name
    FROM public.products p
    WHERE p.id = NEW.product_id;

    NEW.product_name_snapshot :=
      COALESCE(v_product_name, '');

  END IF;


  RETURN NEW;
END;
$$;


CREATE TRIGGER trg_validate_waybill_item_links
  BEFORE INSERT OR UPDATE ON public.waybill_items
  FOR EACH ROW
  EXECUTE FUNCTION public.validate_waybill_item_links();


-- =============================================================================
-- 17. WAYBILL MUST HAVE AT LEAST ONE ITEM BEFORE ISSUE
-- =============================================================================

CREATE OR REPLACE FUNCTION public.ensure_waybill_has_items()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN

  IF NEW.status IN (
    'issued',
    'loading_confirmed'
  )
  THEN

    IF NOT EXISTS (
      SELECT 1
      FROM public.waybill_items wi
      WHERE wi.waybill_id = NEW.id
        AND wi.deleted_at IS NULL
    )
    THEN

      RAISE EXCEPTION
        'Waybill % must contain at least one active item before it can be issued',
        NEW.id;

    END IF;

  END IF;


  RETURN NEW;
END;
$$;


CREATE CONSTRAINT TRIGGER trg_waybill_must_have_items
  AFTER INSERT OR UPDATE OF status ON public.waybills
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  EXECUTE FUNCTION public.ensure_waybill_has_items();


-- =============================================================================
-- 18. CREATE LOADING RECORD WHEN WAYBILL IS ISSUED
-- =============================================================================

CREATE OR REPLACE FUNCTION public.ensure_loading_for_issued_waybill()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN

  IF NEW.status = 'issued'
     AND NEW.deleted_at IS NULL
  THEN

    INSERT INTO public.loading (
      company_id,
      waybill_id,
      status,
      loading_date
    )
    VALUES (
      NEW.company_id,
      NEW.id,
      'pending',
      NEW.waybill_date
    )

    ON CONFLICT (
      company_id,
      waybill_id
    )
    WHERE deleted_at IS NULL
    DO NOTHING;

  END IF;


  RETURN NEW;
END;
$$;


CREATE TRIGGER trg_create_loading_on_waybill_issue
  AFTER INSERT OR UPDATE OF status ON public.waybills
  FOR EACH ROW
  EXECUTE FUNCTION public.ensure_loading_for_issued_waybill();


-- =============================================================================
-- 19. SYNC WAYBILL STATUS WITH LOADING
-- =============================================================================
--
-- loading.pending
--      ↓
-- loading.confirmed
--      ↓
-- waybill.loading_confirmed
--
-- loading.cancelled
--      ↓
-- waybill.cancelled
-- =============================================================================

CREATE OR REPLACE FUNCTION public.sync_waybill_status_from_loading()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN

  IF NEW.status = 'confirmed' THEN

    UPDATE public.waybills
    SET status = 'loading_confirmed'
    WHERE id = NEW.waybill_id
      AND company_id = NEW.company_id
      AND status = 'issued';


  ELSIF NEW.status = 'cancelled' THEN

    UPDATE public.waybills
    SET status = 'cancelled'
    WHERE id = NEW.waybill_id
      AND company_id = NEW.company_id
      AND status = 'issued';

  END IF;


  RETURN NEW;
END;
$$;


CREATE TRIGGER trg_sync_waybill_status_from_loading
  AFTER INSERT OR UPDATE OF status ON public.loading
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_waybill_status_from_loading();


-- =============================================================================
-- 20. RLS
-- =============================================================================

ALTER TABLE public.waybills
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.waybill_items
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.loading
  ENABLE ROW LEVEL SECURITY;


-- =============================================================================
-- 21. WAYBILLS RLS
-- =============================================================================

CREATE POLICY waybills_company_isolation
  ON public.waybills
  FOR ALL
  TO authenticated
  USING (
    company_id = public.auth_user_company_id()
  )
  WITH CHECK (
    company_id = public.auth_user_company_id()
  );


-- =============================================================================
-- 22. WAYBILL ITEMS RLS
-- =============================================================================

CREATE POLICY waybill_items_company_isolation
  ON public.waybill_items
  FOR ALL
  TO authenticated
  USING (
    company_id = public.auth_user_company_id()
  )
  WITH CHECK (
    company_id = public.auth_user_company_id()
  );


-- =============================================================================
-- 23. LOADING RLS
-- =============================================================================

CREATE POLICY loading_company_isolation
  ON public.loading
  FOR ALL
  TO authenticated
  USING (
    company_id = public.auth_user_company_id()
  )
  WITH CHECK (
    company_id = public.auth_user_company_id()
  );


-- =============================================================================
-- 24. GRANTS
-- =============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.waybills
TO authenticated;


GRANT SELECT, INSERT, UPDATE, DELETE
ON public.waybill_items
TO authenticated;


GRANT SELECT, INSERT, UPDATE, DELETE
ON public.loading
TO authenticated;


-- =============================================================================
-- 25. SEQUENCE PERMISSIONS
-- =============================================================================

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO authenticated;


-- =============================================================================
-- END
-- =============================================================================

COMMIT;