-- =============================================================================
-- Gypsum Sales CRM — Core Business Audit Log
-- =============================================================================
-- Reuses the existing public.activity_logs table.
-- Audit entries are generated by database triggers.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. Generic audit trigger function
-- =============================================================================

CREATE OR REPLACE FUNCTION public.audit_core_business_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_company_id uuid;
  v_entity_id uuid;
  v_user_id uuid;
  v_action public.activity_action;
  v_changes jsonb;
  v_description text;
BEGIN
  v_user_id := auth.uid();

  IF TG_OP = 'INSERT' THEN
    v_company_id := NEW.company_id;
    v_entity_id := NEW.id;
    v_action := 'create';

    v_changes := jsonb_build_object(
      'new', to_jsonb(NEW)
    );

    v_description := format(
      'ایجاد %s',
      TG_TABLE_NAME
    );

  ELSIF TG_OP = 'DELETE' THEN
    v_company_id := OLD.company_id;
    v_entity_id := OLD.id;
    v_action := 'delete';

    v_changes := jsonb_build_object(
      'old', to_jsonb(OLD)
    );

    v_description := format(
      'حذف %s',
      TG_TABLE_NAME
    );

  ELSE
    v_company_id := NEW.company_id;
    v_entity_id := NEW.id;

    IF NEW.deleted_at IS NOT NULL
       AND OLD.deleted_at IS NULL
    THEN
      v_action := 'delete';

      v_description := format(
        'غیرفعال‌سازی/حذف نرم %s',
        TG_TABLE_NAME
      );
    ELSE
      v_action := 'update';

      v_description := format(
        'ویرایش %s',
        TG_TABLE_NAME
      );
    END IF;

    v_changes := jsonb_build_object(
      'old', to_jsonb(OLD),
      'new', to_jsonb(NEW)
    );
  END IF;

  INSERT INTO public.activity_logs (
    company_id,
    user_id,
    action,
    entity_type,
    entity_id,
    description,
    changes,
    source
  )
  VALUES (
    v_company_id,
    v_user_id,
    v_action,
    TG_TABLE_NAME,
    v_entity_id,
    v_description,
    v_changes,
    'manual'
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$function$;

COMMENT ON FUNCTION public.audit_core_business_change() IS
  'Writes database-generated audit snapshots into activity_logs for core CRM entities.';


-- =============================================================================
-- 2. Audit triggers
-- =============================================================================

DROP TRIGGER IF EXISTS trg_audit_customers
  ON public.customers;

CREATE TRIGGER trg_audit_customers
  AFTER INSERT OR UPDATE OR DELETE
  ON public.customers
  FOR EACH ROW
  EXECUTE FUNCTION public.audit_core_business_change();


DROP TRIGGER IF EXISTS trg_audit_orders
  ON public.orders;

CREATE TRIGGER trg_audit_orders
  AFTER INSERT OR UPDATE OR DELETE
  ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.audit_core_business_change();


DROP TRIGGER IF EXISTS trg_audit_order_items
  ON public.order_items;

CREATE TRIGGER trg_audit_order_items
  AFTER INSERT OR UPDATE OR DELETE
  ON public.order_items
  FOR EACH ROW
  EXECUTE FUNCTION public.audit_core_business_change();


DROP TRIGGER IF EXISTS trg_audit_waybills
  ON public.waybills;

CREATE TRIGGER trg_audit_waybills
  AFTER INSERT OR UPDATE OR DELETE
  ON public.waybills
  FOR EACH ROW
  EXECUTE FUNCTION public.audit_core_business_change();


DROP TRIGGER IF EXISTS trg_audit_waybill_items
  ON public.waybill_items;

CREATE TRIGGER trg_audit_waybill_items
  AFTER INSERT OR UPDATE OR DELETE
  ON public.waybill_items
  FOR EACH ROW
  EXECUTE FUNCTION public.audit_core_business_change();


DROP TRIGGER IF EXISTS trg_audit_loading
  ON public.loading;

CREATE TRIGGER trg_audit_loading
  AFTER INSERT OR UPDATE OR DELETE
  ON public.loading
  FOR EACH ROW
  EXECUTE FUNCTION public.audit_core_business_change();


DROP TRIGGER IF EXISTS trg_audit_monthly_targets
  ON public.monthly_targets;

CREATE TRIGGER trg_audit_monthly_targets
  AFTER INSERT OR UPDATE OR DELETE
  ON public.monthly_targets
  FOR EACH ROW
  EXECUTE FUNCTION public.audit_core_business_change();


-- =============================================================================
-- 3. Audit query index
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_activity_logs_entity_action_created
  ON public.activity_logs (
    company_id,
    entity_type,
    action,
    created_at DESC
  )
  WHERE deleted_at IS NULL;


-- =============================================================================
-- 4. Prevent ordinary authenticated users from writing audit history
-- =============================================================================

DROP POLICY IF EXISTS activity_logs_company_insert
  ON public.activity_logs;

CREATE POLICY activity_logs_no_authenticated_write
  ON public.activity_logs
  FOR INSERT
  TO authenticated
  WITH CHECK (false);


CREATE POLICY activity_logs_no_authenticated_update
  ON public.activity_logs
  FOR UPDATE
  TO authenticated
  USING (false)
  WITH CHECK (false);


CREATE POLICY activity_logs_no_authenticated_delete
  ON public.activity_logs
  FOR DELETE
  TO authenticated
  USING (false);


COMMIT;